### PR TITLE
Upgrading Notebooks to Atoti Python API version 0.8.10

### PR DESCRIPTION
**Pull request by andrewyang94**
This PR updates the `poetry.lock` file using `poetry update` and upgrades all academy and technical use case guides, and one use case finance notebook to version `0.8.10`. READMEs will also be updated accordingly.

Specifically, for this upgrade, the following fixes will be made:
* Deprecated functions are updated to the current version counterparts.
* Broken widget filters are fixed.
* Broken doc links are fixed.
* `atoti-jupyterlab` column widths are fixed/better spaced (so users can see full columns and not just ellipses).
* MermaidJS diagrams are saved as PNGs and can be viewed in GitHub + browser (thanks @tibdex!).
* Minor paragraph/text spacing adjustments to make things more visually clean (clustering text together rather than having too many line breaks, but not all the time — we must strike a balance).

> **Note:** I used `find . name "*.ipynb" | sort` at the root of the repo to obtain the below list of notebooks.

## Upgraded Notebooks

- [x] ./01-atoti-academy/introduction-to-atoti/main.ipynb
    - [x] **NEEDS FIX:** Broken widgets
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x] **NEEDS FIX:** Broken widget filters
    - [x] **NEEDS FIX:** Deprecated functions
    - [x] **NEEDS FIX:** Missing banners
- [x] ./01-atoti-academy/storytelling-with-atoti/01-Storytelling.ipynb
    - [x] **NEEDS FIX:** Missing banners
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x] **NEEDS FIX:** Deprecated functions
- [x] ./01-atoti-academy/storytelling-with-atoti/02-Storytelling.ipynb
    - [x] **NEEDS FIX:** Missing banners
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./01-atoti-academy/storytelling-with-atoti/03-Storytelling.ipynb
    - [x] **NEEDS FIX:** Missing banners
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./02-technical-guides/aggregate-provider/main.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x] **NEEDS FIX:** Needs data files added to `.gitignore`
- [x] ./02-technical-guides/auto-cube/main-advanced.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./02-technical-guides/auto-cube/main.ipynb
- [x] ./02-technical-guides/conditional-functions/main.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x] **NEEDS FIX:** Needs data files added to `.gitignore`
- [x] ./02-technical-guides/currency-conv-with-weighted-ave/main.ipynb
- [x] ./02-technical-guides/currency-conversion-with-lookup/main.ipynb
    - [x] **NEEDS FIX:** Deprecated functions
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./02-technical-guides/currency-conversion/main.ipynb
    - [x] **NEEDS FIX:** Deprecated functions
- [ ] ./02-technical-guides/directquery-intro/main.ipynb <-- **Skipping, see `0.8.9` PR**
- [ ] ./02-technical-guides/directquery-vector/main.ipynb <-- **Skipping, see `0.8.9` PR**
- [x] ./02-technical-guides/excel-and-atoti/main.ipynb
    - [x] **NEEDS FIX:** Deprecated functions
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./02-technical-guides/internationalization/main.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./02-technical-guides/introductory-tutorial/main.ipynb
    - [x] **NEEDS FIX:** Missing banners
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./02-technical-guides/multidimensional-analysis/main.ipynb
    - [x] **NEEDS FIX:** Missing banners
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./02-technical-guides/rollup-hierarchies/main.ipynb <-- **this works, but we link sample data from a Russian site??** 👀 
    - [x] **NEEDS FIX:** Needs data files added to `.gitignore`
- [x] ./02-technical-guides/security-implementation/01-Basic-authentication.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
- [ ] ./02-technical-guides/security-implementation/02-OIDC-Auth0.ipynb <-- **Skipping, see `0.8.9` PR**
- [ ] ./02-technical-guides/security-implementation/03-OIDC-Google.ipynb <-- **Skipping, see `0.8.9` PR**
- [x] ./02-technical-guides/security-implementation/04-LDAP.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./02-technical-guides/security-implementation/main.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./02-technical-guides/table-creation-and-data-loads/main.ipynb
- [x] ./02-technical-guides/topcount/atoti.ipynb
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./02-technical-guides/topcount/pandas.ipynb
- [ ] ./02-technical-guides/var-benchmark/data_generator.ipynb <-- **Skipping, see `0.8.9` PR**
- [ ] ./02-technical-guides/var-benchmark/main.ipynb <-- **Skipping, see `0.8.9` PR**
- [ ] ./02-technical-guides/virtual-hierarchies/main.ipynb <-- **Skipping, see `0.8.9` PR**
- [x] ./02-technical-guides/weighted-averages/main.ipynb
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./03-use-cases/01-finance/portfolio-management/cvar-optimizer/01_data_generation.ipynb
    - [x] **NEEDS FIX:** Needs data files added to `.gitignore`
- [x] ./03-use-cases/01-finance/portfolio-management/cvar-optimizer/main.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
- [x] ./03-use-cases/01-finance/quantitative-strategy/bucket-analysis/main.ipynb
    - [x] **NEEDS FIX:** Broken doc + index links
    - [x]  **NEEDS FIX:** Deprecated functions
- [x] ./03-use-cases/01-finance/retail-banking/credit-card-analytics/cc_data_processing.ipynb
- [x] ./03-use-cases/01-finance/retail-banking/credit-card-analytics/main.ipynb
    - [x]  **NEEDS FIX:** Deprecated functions

### CODE REVIEW

**Comment by tibdex** [comment]
Don't forget about https://github.com/activeviam/atoti-python-api/pull/4807#discussion_r1493071409 ;)

**Comment by andrewyang94** [comment]
I manually had to add `03-use-cases/01-finance/portfolio-management/cvar-optimizer` to the `test_exclusions.txt` because this was failing our CI checks (https://github.com/atoti/atoti/actions/runs/8289148503/job/22685038382?pr=859#step:8:38). Therefore, we either need to set up our CI checks to use a license to test our "locked" Atoti Python API notebooks, or modify the README generator to exclude these notebooks automatically (leaning toward option 1).

Note: I know our README generator does automatically exclude notebooks, but looks like only ones that are not deemed as "latest version". Thus, in this case, I upgraded the notebook to `0.8.10` and it was added to the list of "testable notebooks".

**Review by printhellohetal — APPROVED** [review]

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Review by printhellohetal — APPROVED** [review]
Slow to review on a plane... but good to go :)

**Pull request merged**
